### ISSUE TITLE
Change data_ field

### ISSUE THREAD

**Issue by stevenarditti** [akvashi24/cs4500-A1-part2#3]
Since the get and remove methods return an Object* in array.h, we believe the data_ field should be a list of Object pointers instead of a list of Objects. In other words, Object* data_  --->  Object** data_. It would help us out if the spec was changed to reflect this.

Please ensure that the test cases still work with this change as well.

**Comment by akvashi24** [comment]
Made the change, and I think it's reflected in the test cases.  Please follow up if I'm wrong.
