### ISSUE TITLE
Float Equality

### ISSUE THREAD

**Issue by j-Myles** [akvashi24/cs4500-A1-part2#7]
This line:

    assert(ia->remove(0) == 3.1);

Does NOT work the way you think it does. C++ does not support direct float equality comparisons in this way (Where the float is wrapped in another object). PLEASE change it to 

     assert(3.11 >= ia->remove(0) >= 3.09);

**Comment by stevenarditti** [comment]
Thank you for bringing this up, I was actually in the middle of opening an issue about this myself.
I was the one who pull requested this change in without realizing my mistake. A fix would be appreciated.

**Comment by j-Myles** [comment]
Also my mistake, assertions require && to perform double equality checks in C++ so a fix might look like:

float r = ia->remove(0);
assert((3.11 >= r) && (r >= 3.09));

**Comment by akvashi24** [comment]
Thanks for this.  I scanned the tests, but didn't think about float equality.  Let me know if I broke something.
